export const GET_CHARACTERS_START = 'GET_CHARACTERS_START'
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS'
export const GET_CHARACTERS_FAIL = 'GET_CHARACTERS_FAIL'

export const GET_SELECTED_CHARACTER_START = 'GET_SELECTED_CHARACTER_START'
export const GET_SELECTED_CHARACTER_SUCCESS = 'GET_SELECTED_CHARACTER_SUCCESS'
export const GET_SELECTED_CHARACTER_FAIL = 'GET_SELECTED_CHARACTER_FAIL'